[browser]
gatherUsageStats = false

[client]
showErrorDetails = true
toolbarMode = "developer"

[logger]
level = "info"

[theme]
base="light"
primaryColor="#FF4B4B"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#31333F"
font="sans serif"

[server]
port = 8501
address = "localhost"
fileWatcherType = "auto"
headless = false
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200
enableStaticServing = true
runOnSave = true